### ISSUE TITLE
Regression time limit exceeded / TimeoutError

### ISSUE THREAD

**Issue by ldez** [letsencrypt/pebble#440]
Hello,

since the merge of https://github.com/letsencrypt/pebble/pull/420, there a problem of timeout.

I observed that on lego but you have the same problem on your CI:

https://ci.appveyor.com/project/jsha/pebble/builds/49233994?fullLog=true

```
DEBUG:acme.client:Storing nonce: uheLwx93nDxWtXFPxcGvlA
Traceback (most recent call last):
  File ".\test\chisel2.py", line 209, in <module>
    auth_and_issue(domains)
  File ".\test\chisel2.py", line 122, in auth_and_issue
    order = client.poll_and_finalize(order)
  File "c:\projects\pebble\certbot\acme\acme\client.py", line 185, in poll_and_finalize
    return self.finalize_order(orderr, deadline)
  File "c:\projects\pebble\certbot\acme\acme\client.py", line 275, in finalize_order
    return self.poll_finalization(orderr, deadline, fetch_alternative_chains)
  File "c:\projects\pebble\certbot\acme\acme\client.py", line 259, in poll_finalization
    raise errors.TimeoutError()
acme.errors.TimeoutError
```

**Comment by ldez** [comment]
For now, I haven't diagnosed the exact reason for this regression (except it's related to the PR).

Maybe @mcpherrinm, you will see the problem quicker than me.

**Comment by mcpherrinm** [comment]
Interesting! I’ll take a look

**Comment by ldez** [comment]
The order status seems to stay on `processing` :thinking:

**Comment by ldez** [comment]
I found the problem:
```go
if len(domains) == 0 || len(ips) == 0 {
```

should be 
```
if len(domains) == 0 && len(ips) == 0 {
```

**Comment by ldez** [comment]
I created a PR #441
